let string1='Clarity TTS';
let string2='Chennai';
let string3=string1.concat(string2);
console.log(string3);
console.log(string1.indexOf('l'));
console.log(string1.charAt(2));
console.log(string2);
console.log(string1.replace('tts','travel technology solutions'));
let string4=string1.split(" ");
console.log(string4);
for(let i=0;i<string1.length;i++)
console.log(string1.charAt(i));
console.log(string1.substr(1,3));
console.log(string1.substring(1,3));
console.log(string1.slice(1,3));
console.log(string1.toLowerCase());
console.log(string1.toUpperCase());
let string5='    OMR';
console.log(string5.trim());
console.log(string1.includes('la','TTS','ty','apple'));
console.log(string1.search("l"));
let name="My Name is \"Priya\"";
console.log(name);
let name1="My Name is \"Priya\"";
console.log(name1);
let name2="My Name is \\Priya\\";
console.log(name2);
let name3="My Name is \nPriya";
console.log(name3);
let name4="My Name is \rPreethi";
console.log(name4);
let name5="My Name is \vPriya";
console.log(name5);
let name6="My Name is \tPriya";
console.log(name6);
let name7="My Name is\bPriya";
console.log(name7);
let name8="My Name is \fPriya\f";
console.log(name8);
let s1="preethi";
let s2="preethi";
let s3=new String("preethi");
console.log(s1==s2);
console.log(s1==s3);
